BEGIN TRANSACTION;

CREATE TABLE HOSTEL (HOSTEL_NAME TEXT PRIMARY KEY , 
STREET TEXT, CITY TEXT, STATE TEXT, POSTAL_CODE TEXT , COUNTRY TEXT,
CHECKIN_TIME TEXT, CHECKOUT_TIME TEXT,SMOKING TEXT,ALCOHOL TEXT,cancellation_deadline INTEGER, cancellation_penalty DOUBLE, 
PHONE TEXT,EMAIL TEXT,FACEBOOK TEXT, WEB TEXT);

CREATE TABLE AVAILABILITY (
AVAILABILITY_ID INTEGER PRIMARY KEY autoincrement,
DATE TEXT,
ROOM INTEGER,
BED INTEGER,
HOSTEL_NAME references hostel(HOSTEL_NAME),
PRICE DOUBLE,
STATUS INTEGER NOT NULL,
UNIQUE(DATE,ROOM,BED,HOSTEL_NAME)
);

CREATE TABLE CUSTOMER (CUST_ID INTEGER PRIMARY KEY autoincrement,EMAIL TEXT UNIQUE,FIRST_NAME TEXT NOT NULL,LAST_NAME TEXT NOT NULL,
PHONE TEXT,TWITTER TEXT,FACEBOOK TEXT,CC_NUMBER TEXT,
CC_EXPIRE_DATE TEXT, 
BILLING_NAME TEXT, 
CC_SECURITY_CODE,
CREATE_DATE TEXT
);

CREATE TABLE BOOKING (
BOOKING_ID INTEGER PRIMARY KEY autoincrement, 
HOSTEL_NAME TEXT NOT NULL REFERENCES HOSTEL (HOSTEL_NAME),
CHECKIN_DATE TEXT NOT NULL, CHECKOUT_DATE TEXT NOT NULL,
STATUS TEXT NOT NULL,
CUST_ID TEXT NOT NULL REFERENCES CUSTOMER (CUST_ID),
NO_OF_ROOMS INTEGER NOT NULL,
BOOKING_PRICE REAL, CANCEL_FEE REAL, 
CREATE_DATE TEXT,CREATE_USER TEXT, UPDATE_DATE TEXT,UPDATE_USER TEXT
);


CREATE TABLE BOOKING_DETAILS (BOOKING_ID INTEGER NOT NULL REFERENCES BOOKING (BOOKING_ID),AVAILABILITY_ID INTEGER NOT NULL REFERENCES AVAILABILITY (AVAILABILITY_ID));

CREATE TABLE USER (USER_ID TEXT PRIMARY KEY,PASSWORD TEXT NOT NULL,USER_TYPE TEXT NOT NULL, FIRST_NAME TEXT NOT NULL, LAST_NAME TEXT NOT NULL,EXPIRE_DATE TEXT);
insert into USER (USER_ID,PASSWORD,USER_TYPE, FIRST_NAME, LAST_NAME)
values ('admin','admin','admin','Admin','Owner');
COMMIT;
